server:
  port: 80

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/testmysql?serverTimezone=UTC
      username: root
      password: root

logging:
  level:
    root: info
  logback:
    rollingpolicy:
      max-file-size: 10KB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
  file:
    name: server.log